name: Install Dependencies
description: Install required project dependencies
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies for .
      run: pnpm install
      shell: bash
