name: CI (Pull Request)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v2 
    
        # Setup the node js environment on runner instance
        - name: Set up Node.js environment
          uses: actions/setup-node@v2
          with:
            node-version: '18'